// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ehealthcare.Model;

namespace HospitalLibrary.Migrations
{
    [DbContext(typeof(HospitalDbContext))]
    partial class HospitalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("HospitalLibrary.FeedbackAndSurvey.Model.PatientFeedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("Anonymous")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<string>("PatientUsername")
                        .HasColumnType("text");

                    b.Property<bool>("PublishAllowed")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("SubmissionDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PatientFeedbacks");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Anonymous = false,
                            IsPublished = true,
                            PatientUsername = "imbiamba",
                            PublishAllowed = true,
                            SubmissionDate = new DateTime(2021, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "Sehr gut!"
                        },
                        new
                        {
                            Id = 1,
                            Anonymous = false,
                            IsPublished = false,
                            PatientUsername = "imbiamba",
                            PublishAllowed = false,
                            SubmissionDate = new DateTime(2021, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "alallalal"
                        });
                });

            modelBuilder.Entity("HospitalLibrary.FeedbackAndSurvey.Model.Question", b =>
                {
                    b.Property<int>("SurveyId")
                        .HasColumnType("integer");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("SurveyId", "Id");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            SurveyId = -1,
                            Id = -1,
                            Category = 1,
                            Value = 1
                        });
                });

            modelBuilder.Entity("HospitalLibrary.FeedbackAndSurvey.Model.Survey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("PatientId")
                        .HasColumnType("text");

                    b.Property<DateTime>("SubmissionDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("VisitId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("Surveys");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            PatientId = "imbiamba",
                            SubmissionDate = new DateTime(2021, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VisitId = 1
                        });
                });

            modelBuilder.Entity("HospitalLibrary.GraphicalEditor.Model.ExteriorGraphic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<double>("Height")
                        .HasColumnType("double precision");

                    b.Property<int>("IdElement")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<double>("Width")
                        .HasColumnType("double precision");

                    b.Property<double>("X")
                        .HasColumnType("double precision");

                    b.Property<double>("Y")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("ExteriorGraphic");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Height = 200.0,
                            IdElement = 0,
                            Name = "ZGR1",
                            Type = "building",
                            Width = 100.0,
                            X = 180.0,
                            Y = 30.0
                        },
                        new
                        {
                            Id = 2,
                            Height = 110.0,
                            IdElement = 1,
                            Name = "ZGR2",
                            Type = "building",
                            Width = 180.0,
                            X = 380.0,
                            Y = 120.0
                        },
                        new
                        {
                            Id = 7,
                            Height = 50.0,
                            IdElement = -1,
                            Name = "",
                            Type = "road",
                            Width = 600.0,
                            X = 0.0,
                            Y = 250.0
                        },
                        new
                        {
                            Id = 3,
                            Height = 110.0,
                            IdElement = -1,
                            Name = "",
                            Type = "road",
                            Width = 50.0,
                            X = 0.0,
                            Y = 290.0
                        },
                        new
                        {
                            Id = 4,
                            Height = 400.0,
                            IdElement = -1,
                            Name = "",
                            Type = "road",
                            Width = 50.0,
                            X = 305.0,
                            Y = 0.0
                        },
                        new
                        {
                            Id = 5,
                            Height = 80.0,
                            IdElement = -1,
                            Name = "P",
                            Type = "parking",
                            Width = 50.0,
                            X = 245.0,
                            Y = 310.0
                        },
                        new
                        {
                            Id = 6,
                            Height = 80.0,
                            IdElement = -1,
                            Name = "P",
                            Type = "parking",
                            Width = 50.0,
                            X = 380.0,
                            Y = 20.0
                        });
                });

            modelBuilder.Entity("HospitalLibrary.GraphicalEditor.Model.FloorGraphic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("BuildingId")
                        .HasColumnType("integer");

                    b.Property<long>("Floor")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("FloorGraphics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BuildingId = 0,
                            Floor = 0L
                        },
                        new
                        {
                            Id = 2,
                            BuildingId = 0,
                            Floor = 1L
                        });
                });

            modelBuilder.Entity("HospitalLibrary.GraphicalEditor.Model.RoomEquipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RoomEquipments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Bed",
                            Quantity = 2,
                            RoomId = 1,
                            Type = "Static"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Needle",
                            Quantity = 200,
                            RoomId = 2,
                            Type = "Dynamic"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Needle",
                            Quantity = 300,
                            RoomId = 3,
                            Type = "Dynamic"
                        });
                });

            modelBuilder.Entity("HospitalLibrary.MedicalRecords.Model.Allergen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Allergens");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "macija dlaka"
                        });
                });

            modelBuilder.Entity("HospitalLibrary.MedicalRecords.Model.MedicalRecord", b =>
                {
                    b.Property<string>("PatientId")
                        .HasColumnType("text");

                    b.Property<int>("BloodType")
                        .HasColumnType("integer");

                    b.Property<string>("DoctorId")
                        .HasColumnType("text");

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<string>("PersonalId")
                        .HasColumnType("text");

                    b.Property<string>("Profession")
                        .HasColumnType("text");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.HasKey("PatientId");

                    b.HasIndex("DoctorId");

                    b.ToTable("MedicalRecords");

                    b.HasData(
                        new
                        {
                            PatientId = "imbiamba",
                            BloodType = 4,
                            DoctorId = "nelex",
                            Height = 186,
                            PersonalId = "1209001129123",
                            Profession = "Professor",
                            Weight = 90
                        });
                });

            modelBuilder.Entity("HospitalLibrary.Model.PatientAllergen", b =>
                {
                    b.Property<string>("PatientId")
                        .HasColumnType("text");

                    b.Property<int>("AllergenId")
                        .HasColumnType("integer");

                    b.HasKey("PatientId", "AllergenId");

                    b.HasIndex("AllergenId");

                    b.ToTable("PatientAllergens");

                    b.HasData(
                        new
                        {
                            PatientId = "imbiamba",
                            AllergenId = 1
                        });
                });

            modelBuilder.Entity("HospitalLibrary.RoomsAndEquipment.Model.TermOfRelocationEquipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("FinishedRelocation")
                        .HasColumnType("boolean");

                    b.Property<int>("IdDestinationRoom")
                        .HasColumnType("integer");

                    b.Property<int>("IdSourceRoom")
                        .HasColumnType("integer");

                    b.Property<string>("NameOfEquipment")
                        .HasColumnType("text");

                    b.Property<int>("QuantityOfEquipment")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("durationInMinutes")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("TermOfRelocationEquipments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndTime = new DateTime(2021, 11, 22, 1, 10, 0, 0, DateTimeKind.Unspecified),
                            FinishedRelocation = false,
                            IdDestinationRoom = 8,
                            IdSourceRoom = 7,
                            NameOfEquipment = "bed",
                            QuantityOfEquipment = 2,
                            StartTime = new DateTime(2021, 11, 22, 1, 0, 0, 0, DateTimeKind.Unspecified),
                            durationInMinutes = 10
                        },
                        new
                        {
                            Id = 2,
                            EndTime = new DateTime(2021, 11, 22, 4, 10, 0, 0, DateTimeKind.Unspecified),
                            FinishedRelocation = false,
                            IdDestinationRoom = 9,
                            IdSourceRoom = 7,
                            NameOfEquipment = "needle",
                            QuantityOfEquipment = 14,
                            StartTime = new DateTime(2021, 11, 22, 3, 30, 0, 0, DateTimeKind.Unspecified),
                            durationInMinutes = 40
                        },
                        new
                        {
                            Id = 3,
                            EndTime = new DateTime(2021, 11, 23, 7, 45, 0, 0, DateTimeKind.Unspecified),
                            FinishedRelocation = false,
                            IdDestinationRoom = 9,
                            IdSourceRoom = 8,
                            NameOfEquipment = "infusion",
                            QuantityOfEquipment = 8,
                            StartTime = new DateTime(2021, 11, 23, 7, 30, 0, 0, DateTimeKind.Unspecified),
                            durationInMinutes = 15
                        },
                        new
                        {
                            Id = 4,
                            EndTime = new DateTime(2021, 11, 23, 9, 25, 0, 0, DateTimeKind.Unspecified),
                            FinishedRelocation = false,
                            IdDestinationRoom = 11,
                            IdSourceRoom = 9,
                            NameOfEquipment = "table",
                            QuantityOfEquipment = 1,
                            StartTime = new DateTime(2021, 11, 23, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            durationInMinutes = 25
                        },
                        new
                        {
                            Id = 5,
                            EndTime = new DateTime(2021, 11, 23, 11, 15, 0, 0, DateTimeKind.Unspecified),
                            FinishedRelocation = false,
                            IdDestinationRoom = 7,
                            IdSourceRoom = 10,
                            NameOfEquipment = "xrayMachine",
                            QuantityOfEquipment = 1,
                            StartTime = new DateTime(2021, 11, 23, 10, 45, 0, 0, DateTimeKind.Unspecified),
                            durationInMinutes = 30
                        },
                        new
                        {
                            Id = 6,
                            EndTime = new DateTime(2021, 11, 23, 14, 50, 0, 0, DateTimeKind.Unspecified),
                            FinishedRelocation = false,
                            IdDestinationRoom = 11,
                            IdSourceRoom = 10,
                            NameOfEquipment = "chair",
                            QuantityOfEquipment = 5,
                            StartTime = new DateTime(2021, 11, 23, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            durationInMinutes = 20
                        });
                });

            modelBuilder.Entity("ehealthcare.Model.MedicalPermit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("DoctorId")
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PatientId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("MedicalPermits");
                });

            modelBuilder.Entity("ehealthcare.Model.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("Floor")
                        .HasColumnType("integer");

                    b.Property<bool>("IsRenovated")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("IsRenovatedUntill")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("NumOfTakenBeds")
                        .HasColumnType("integer");

                    b.Property<int>("RoomType")
                        .HasColumnType("integer");

                    b.Property<string>("Sector")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 16,
                            Floor = 0,
                            IsRenovated = false,
                            IsRenovatedUntill = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Counter 1",
                            NumOfTakenBeds = 0,
                            RoomType = 4,
                            Sector = "CS"
                        },
                        new
                        {
                            Id = 1,
                            Floor = 0,
                            IsRenovated = false,
                            IsRenovatedUntill = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Counter 2",
                            NumOfTakenBeds = 0,
                            RoomType = 4,
                            Sector = "CS"
                        },
                        new
                        {
                            Id = 2,
                            Floor = 0,
                            IsRenovated = false,
                            IsRenovatedUntill = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Examination room 1",
                            NumOfTakenBeds = 1,
                            RoomType = 0,
                            Sector = "ES"
                        },
                        new
                        {
                            Id = 3,
                            Floor = 0,
                            IsRenovated = false,
                            IsRenovatedUntill = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Examination room 2",
                            NumOfTakenBeds = 1,
                            RoomType = 0,
                            Sector = "ES"
                        },
                        new
                        {
                            Id = 4,
                            Floor = 0,
                            IsRenovated = false,
                            IsRenovatedUntill = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Restroom 1",
                            NumOfTakenBeds = 0,
                            RoomType = 3,
                            Sector = "RRS"
                        },
                        new
                        {
                            Id = 5,
                            Floor = 0,
                            IsRenovated = false,
                            IsRenovatedUntill = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Restroom 2",
                            NumOfTakenBeds = 0,
                            RoomType = 3,
                            Sector = "RRS"
                        },
                        new
                        {
                            Id = 6,
                            Floor = 0,
                            IsRenovated = false,
                            IsRenovatedUntill = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Waiting room 1",
                            NumOfTakenBeds = 0,
                            RoomType = 5,
                            Sector = "WS"
                        },
                        new
                        {
                            Id = 7,
                            Floor = 1,
                            IsRenovated = false,
                            IsRenovatedUntill = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Operation room 1",
                            NumOfTakenBeds = 0,
                            RoomType = 1,
                            Sector = "OS"
                        },
                        new
                        {
                            Id = 8,
                            Floor = 1,
                            IsRenovated = false,
                            IsRenovatedUntill = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Operation room 2",
                            NumOfTakenBeds = 0,
                            RoomType = 1,
                            Sector = "OS"
                        },
                        new
                        {
                            Id = 9,
                            Floor = 1,
                            IsRenovated = false,
                            IsRenovatedUntill = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Operation room 3",
                            NumOfTakenBeds = 0,
                            RoomType = 1,
                            Sector = "OS"
                        },
                        new
                        {
                            Id = 10,
                            Floor = 1,
                            IsRenovated = false,
                            IsRenovatedUntill = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Operation room 4",
                            NumOfTakenBeds = 0,
                            RoomType = 1,
                            Sector = "OS"
                        },
                        new
                        {
                            Id = 11,
                            Floor = 1,
                            IsRenovated = false,
                            IsRenovatedUntill = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Examination room 3",
                            NumOfTakenBeds = 0,
                            RoomType = 0,
                            Sector = "ES"
                        },
                        new
                        {
                            Id = 12,
                            Floor = 1,
                            IsRenovated = false,
                            IsRenovatedUntill = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Examination room 4",
                            NumOfTakenBeds = 0,
                            RoomType = 0,
                            Sector = "ES"
                        },
                        new
                        {
                            Id = 13,
                            Floor = 1,
                            IsRenovated = false,
                            IsRenovatedUntill = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Restroom 3",
                            NumOfTakenBeds = 0,
                            RoomType = 3,
                            Sector = "RRS"
                        },
                        new
                        {
                            Id = 14,
                            Floor = 1,
                            IsRenovated = false,
                            IsRenovatedUntill = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Restroom 4",
                            NumOfTakenBeds = 0,
                            RoomType = 3,
                            Sector = "RRS"
                        },
                        new
                        {
                            Id = 15,
                            Floor = 1,
                            IsRenovated = false,
                            IsRenovatedUntill = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Waiting room 2",
                            NumOfTakenBeds = 0,
                            RoomType = 5,
                            Sector = "WS"
                        });
                });

            modelBuilder.Entity("ehealthcare.Model.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<bool>("IsActivated")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("boolean");

                    b.Property<int>("LoginType")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("ParentName")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .HasColumnType("text");

                    b.Property<Guid>("Token")
                        .HasColumnType("uuid");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("Discriminator").HasValue("User");
                });

            modelBuilder.Entity("ehealthcare.Model.Doctor", b =>
                {
                    b.HasBaseType("ehealthcare.Model.User");

                    b.Property<int>("Specialization")
                        .HasColumnType("integer");

                    b.Property<int>("UsedOffDays")
                        .HasColumnType("integer");

                    b.ToTable("Doctors");

                    b.HasDiscriminator().HasValue("Doctor");

                    b.HasData(
                        new
                        {
                            Id = "nelex",
                            Address = "Sime Milutinovica, 2",
                            City = "Novi Sad",
                            Country = "Serbia",
                            DateOfBirth = new DateTime(1999, 7, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nemanjar@gmail.com",
                            Gender = "male",
                            IsActivated = false,
                            IsBlocked = false,
                            LoginType = 2,
                            Name = "Nemanja",
                            ParentName = "Zoran",
                            Password = "najjacapecurka",
                            Phone = "019919199191",
                            Surname = "Radojcic",
                            Token = new Guid("00000000-0000-0000-0000-000000000000"),
                            Username = "nelex",
                            Specialization = 3,
                            UsedOffDays = 12
                        });
                });

            modelBuilder.Entity("ehealthcare.Model.Patient", b =>
                {
                    b.HasBaseType("ehealthcare.Model.User");

                    b.Property<string>("DoctorId")
                        .HasColumnType("text");

                    b.HasIndex("DoctorId");

                    b.ToTable("Patients");

                    b.HasDiscriminator().HasValue("Patient");

                    b.HasData(
                        new
                        {
                            Id = "imbiamba",
                            Address = "Sime Milosevica, 5",
                            DateOfBirth = new DateTime(2001, 11, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "markoilic@gmail.com",
                            Gender = "male",
                            IsActivated = false,
                            IsBlocked = false,
                            LoginType = 0,
                            Name = "Marko",
                            ParentName = "Milan",
                            Password = "pecurkaa",
                            Phone = "019919199191",
                            Surname = "Ilic",
                            Token = new Guid("17893c3e-07de-4e65-aad1-47964225946f"),
                            Username = "imbiamba"
                        });
                });

            modelBuilder.Entity("HospitalLibrary.FeedbackAndSurvey.Model.Question", b =>
                {
                    b.HasOne("HospitalLibrary.FeedbackAndSurvey.Model.Survey", "Survey")
                        .WithMany("Questions")
                        .HasForeignKey("SurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HospitalLibrary.FeedbackAndSurvey.Model.Survey", b =>
                {
                    b.HasOne("ehealthcare.Model.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId");
                });

            modelBuilder.Entity("HospitalLibrary.GraphicalEditor.Model.FloorGraphic", b =>
                {
                    b.OwnsMany("ehealthcare.Model.RoomGraphic", "RoomGraphics", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                            b1.Property<string>("DoorPosition")
                                .HasColumnType("text");

                            b1.Property<int>("FloorGraphicId")
                                .HasColumnType("integer");

                            b1.Property<int>("Height")
                                .HasColumnType("integer");

                            b1.Property<int>("RoomId")
                                .HasColumnType("integer");

                            b1.Property<int>("Width")
                                .HasColumnType("integer");

                            b1.Property<int>("X")
                                .HasColumnType("integer");

                            b1.Property<int>("Y")
                                .HasColumnType("integer");

                            b1.HasKey("Id");

                            b1.HasIndex("FloorGraphicId");

                            b1.HasIndex("RoomId");

                            b1.ToTable("RoomGraphics");

                            b1.WithOwner()
                                .HasForeignKey("FloorGraphicId");

                            b1.HasOne("ehealthcare.Model.Room", "Room")
                                .WithMany()
                                .HasForeignKey("RoomId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.HasData(
                                new
                                {
                                    Id = 16,
                                    DoorPosition = "right",
                                    FloorGraphicId = 1,
                                    Height = 100,
                                    RoomId = 16,
                                    Width = 100,
                                    X = 0,
                                    Y = 0
                                },
                                new
                                {
                                    Id = 1,
                                    DoorPosition = "right",
                                    FloorGraphicId = 1,
                                    Height = 100,
                                    RoomId = 1,
                                    Width = 100,
                                    X = 0,
                                    Y = 100
                                },
                                new
                                {
                                    Id = 2,
                                    DoorPosition = "right",
                                    FloorGraphicId = 1,
                                    Height = 145,
                                    RoomId = 2,
                                    Width = 75,
                                    X = 0,
                                    Y = 340
                                },
                                new
                                {
                                    Id = 3,
                                    DoorPosition = "left",
                                    FloorGraphicId = 1,
                                    Height = 145,
                                    RoomId = 3,
                                    Width = 75,
                                    X = 222,
                                    Y = 340
                                },
                                new
                                {
                                    Id = 4,
                                    DoorPosition = "top",
                                    FloorGraphicId = 1,
                                    Height = 80,
                                    RoomId = 4,
                                    Width = 147,
                                    X = 0,
                                    Y = 517
                                },
                                new
                                {
                                    Id = 5,
                                    DoorPosition = "top",
                                    FloorGraphicId = 1,
                                    Height = 80,
                                    RoomId = 5,
                                    Width = 147,
                                    X = 150,
                                    Y = 517
                                },
                                new
                                {
                                    Id = 6,
                                    DoorPosition = "none",
                                    FloorGraphicId = 1,
                                    Height = 160,
                                    RoomId = 6,
                                    Width = 140,
                                    X = 150,
                                    Y = 20
                                },
                                new
                                {
                                    Id = 7,
                                    DoorPosition = "right",
                                    FloorGraphicId = 2,
                                    Height = 100,
                                    RoomId = 7,
                                    Width = 100,
                                    X = 0,
                                    Y = 0
                                },
                                new
                                {
                                    Id = 8,
                                    DoorPosition = "left",
                                    FloorGraphicId = 2,
                                    Height = 100,
                                    RoomId = 8,
                                    Width = 100,
                                    X = 197,
                                    Y = 0
                                },
                                new
                                {
                                    Id = 9,
                                    DoorPosition = "right",
                                    FloorGraphicId = 2,
                                    Height = 100,
                                    RoomId = 9,
                                    Width = 100,
                                    X = 0,
                                    Y = 100
                                },
                                new
                                {
                                    Id = 10,
                                    DoorPosition = "left",
                                    FloorGraphicId = 2,
                                    Height = 100,
                                    RoomId = 10,
                                    Width = 100,
                                    X = 197,
                                    Y = 100
                                },
                                new
                                {
                                    Id = 11,
                                    DoorPosition = "right",
                                    FloorGraphicId = 2,
                                    Height = 145,
                                    RoomId = 11,
                                    Width = 75,
                                    X = 0,
                                    Y = 340
                                },
                                new
                                {
                                    Id = 12,
                                    DoorPosition = "left",
                                    FloorGraphicId = 2,
                                    Height = 145,
                                    RoomId = 12,
                                    Width = 75,
                                    X = 222,
                                    Y = 340
                                },
                                new
                                {
                                    Id = 13,
                                    DoorPosition = "top",
                                    FloorGraphicId = 2,
                                    Height = 80,
                                    RoomId = 13,
                                    Width = 147,
                                    X = 0,
                                    Y = 517
                                },
                                new
                                {
                                    Id = 14,
                                    DoorPosition = "top",
                                    FloorGraphicId = 2,
                                    Height = 80,
                                    RoomId = 14,
                                    Width = 147,
                                    X = 150,
                                    Y = 517
                                },
                                new
                                {
                                    Id = 15,
                                    DoorPosition = "none",
                                    FloorGraphicId = 2,
                                    Height = 100,
                                    RoomId = 15,
                                    Width = 140,
                                    X = 10,
                                    Y = 220
                                });
                        });
                });

            modelBuilder.Entity("HospitalLibrary.MedicalRecords.Model.MedicalRecord", b =>
                {
                    b.HasOne("ehealthcare.Model.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId");

                    b.HasOne("ehealthcare.Model.Patient", "Patient")
                        .WithOne("Medical")
                        .HasForeignKey("HospitalLibrary.MedicalRecords.Model.MedicalRecord", "PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HospitalLibrary.Model.PatientAllergen", b =>
                {
                    b.HasOne("HospitalLibrary.MedicalRecords.Model.Allergen", "Allergen")
                        .WithMany("PatientAllergens")
                        .HasForeignKey("AllergenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ehealthcare.Model.Patient", "Patient")
                        .WithMany("PatientAllergens")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ehealthcare.Model.MedicalPermit", b =>
                {
                    b.HasOne("ehealthcare.Model.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId");

                    b.HasOne("ehealthcare.Model.Patient", null)
                        .WithMany("MedicalPermits")
                        .HasForeignKey("PatientId");
                });

            modelBuilder.Entity("ehealthcare.Model.Patient", b =>
                {
                    b.HasOne("ehealthcare.Model.Doctor", null)
                        .WithMany("Patients")
                        .HasForeignKey("DoctorId");
                });
#pragma warning restore 612, 618
        }
    }
}
